### ISSUE TITLE
Conflicting hover colors and no transition on hover activity

### ISSUE THREAD

**Issue by nkirukka** [codewithvoid/AskDevs#62] opened 2022-11-27 09:38 UTC

**Comment by codewithvoid** [comment] 2022-11-27 18:13
Hi @nkirukka. Can you please add more details? What's breaking and proposed intended behaviour?

**Comment by codewithvoid** [comment] 2022-12-07 10:24
@nkirukka friendly ping. Can you please clarify the issue. Use screengrab if possible.

**Comment by accodes21** [comment] 2022-12-12 16:23
I have already removed this conflicted hover colors, and The PR is already merged so you can close this issue

**Comment by codewithvoid** [comment] 2022-12-12 20:15
Thanks @accodes21. Closing this.

**Closed** 2022-12-12 20:15 UTC
Labels: bug
